"""drop legacy price history table

Revision ID: 5fa47aea0ff9
Revises: a5ab589bed35
Create Date: 2026-08-03 23:34:20.717894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fa47aea0ff9'
down_revision: Union[str, Sequence[str], None] = 'a5ab589bed35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_column('products', 'last_checked_at')
    op.drop_column('products', 'competitor_name')
    op.drop_column('products', 'url')
    op.drop_column('products', 'price_selector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price_selector', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('competitor_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('last_checked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('price_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('PriceHistory_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('PriceHistory_pkey'))
    )
    # ### end Alembic commands ###
