"""add competitor tracking fields

Revision ID: 864f5293a3f1
Revises: 
Create Date: 2026-07-29 13:00:48.736178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864f5293a3f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('competitor_name', sa.String(), nullable=True))
    op.add_column('products', sa.Column('last_checked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'last_checked_at')
    op.drop_column('products', 'competitor_name')
    # ### end Alembic commands ###
