"""add product price selector

Revision ID: 8e72d07acd84
Revises: a79db36d35c7
Create Date: 2026-07-31 11:28:37.318191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e72d07acd84'
down_revision: Union[str, Sequence[str], None] = 'a79db36d35c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price_selector', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price_selector')
    # ### end Alembic commands ###
