"""rename product price to our price

Revision ID: a3f583e76409
Revises: 5fa47aea0ff9
Create Date: 2026-08-04 20:04:14.329537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f583e76409'
down_revision: Union[str, Sequence[str], None] = '5fa47aea0ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("products", "price", new_column_name="our_price")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("products", "our_price", new_column_name="price")
    # ### end Alembic commands ###
